spring.application.name=ms-clientes
server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:postgresql://postgres:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT@postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG